import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../theme/colors';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F0F7F0',
    },
    bgCircle1: {
        position: 'absolute',
        width: width * 1.4,
        height: width * 1.4,
        borderRadius: width * 0.7,
        backgroundColor: colors.primary,
        top: -width * 0.6,
        left: -width * 0.2,
    },
    bgCircle2: {
        position: 'absolute',
        width: 160,
        height: 160,
        borderRadius: 80,
        backgroundColor: 'rgba(102, 187, 106, 0.15)',
        top: height * 0.32,
        right: -40,
    },
    bgCircle3: {
        position: 'absolute',
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(46, 125, 50, 0.08)',
        bottom: height * 0.12,
        left: -30,
    },

    floatDot: {
        position: 'absolute',
        borderRadius: 50,
        backgroundColor: 'rgba(46, 125, 50, 0.12)',
    },
    floatDot1: { width: 10, height: 10, top: height * 0.38, left: width * 0.08 },
    floatDot2: { width: 7, height: 7, top: height * 0.52, right: width * 0.1 },
    floatDot3: { width: 14, height: 14, bottom: height * 0.2, right: width * 0.25 },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 40,
    },
    headerSection: {
        alignItems: 'center',
        paddingTop: height * 0.1,
        paddingBottom: 50,
    },
    iconContainer: {
        marginBottom: 16,
    },
    iconInner: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: 'rgba(255,255,255,0.22)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2.5,
        borderColor: 'rgba(255,255,255,0.4)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
    },
    appName: {
        fontSize: 14,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.7)',
        letterSpacing: 3,
        textTransform: 'uppercase',
        marginBottom: 6,
    },
    welcomeText: {
        fontSize: 30,
        fontWeight: '800',
        color: '#fff',
        letterSpacing: 0.5,
        marginBottom: 6,
    },
    subtitleText: {
        fontSize: 15,
        color: 'rgba(255,255,255,0.75)',
        fontWeight: '400',
        letterSpacing: 0.3,
    },
    formCard: {
        marginHorizontal: 20,
        backgroundColor: '#fff',
        borderRadius: 28,
        padding: 24,
        paddingTop: 28,
        paddingBottom: 28,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 24,
        elevation: 8,
    },
    footer: {
        marginTop: 28,
        paddingHorizontal: 24,
        alignItems: 'center',
    },
    dividerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        width: '100%',
        paddingHorizontal: 20,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: 'rgba(46, 125, 50, 0.15)',
    },
    dividerText: {
        marginHorizontal: 14,
        color: '#999',
        fontSize: 13,
        fontWeight: '500',
    },
    signupButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        paddingVertical: 14,
        paddingHorizontal: 28,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: 'rgba(46, 125, 50, 0.2)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
        width: '100%',
        maxWidth: 300,
    },
    signupButtonText: {
        color: colors.primary,
        fontSize: 15,
        fontWeight: '700',
        marginLeft: 8,
        letterSpacing: 0.3,
    },
});
